name: xeus-clang-repl
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - clangdev
  - cmake
  # Host dependencies
  - xeus
  - xtensor
  - xtensor-blas
  - nlohmann_json
  - cppzmq
  - xtl
  - pugixml
  - cxxopts
  - libuuid
  # Test dependencies
  - pytest
  - jupyter_kernel_test
