name: xeus-clang-repl
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - clangdev>=15
  - cmake
  # Host dependencies
  - xeus>=2.0,<3.0
  - nlohmann_json>=3.9.1,<3.10
  - cppzmq>=4.6.0,<5
  - xtl>=0.7,<0.8
  - pugixml
  - cxxopts>=2.1.1,<2.2
  - libuuid
  - xtensor
  - xtensor-blas
  # Test dependencies
  - pytest
  - jupyter_kernel_test
