#!/bin/bash
exit 0

# Build, cache and install Clang-dev
mkdir clang-dev
cd clang-dev
git clone --depth=1 --branch release/14.x --single-branch https://github.com/llvm/llvm-project.git
#patch
cd llvm-project
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=host -DLLVM_OPTIMIZED_TABLEGEN=On -DLLVM_ENABLE_PROJECTS=clang ../llvm
make ClangDriverOptions clang-repl
clangbuild=`pwd`
export PATH=$clangbuild/bin:$PATH
export LD_LIBRARY_PATH=$clangbuild/lib:$LD_LIBRARY_PATH
cd ../../..

# Build and Install xeus-clang-repl
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=$KERNEL_PYTHON_PREFIX -DCMAKE_INSTALL_PREFIX=$KERNEL_PYTHON_PREFIX -DCMAKE_INSTALL_LIBDIR=lib -DLLVM_USE_LINKER=gold ..
make install
